name: Run MiniKube setup
on: [workflow_dispatch]
jobs:
  Provision:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run minikube Setup
        run: /usr/local/bin/ansible-playbook -i minikube-internal.banecio-devops.online, tool-setup.yml -e ansible_user=${{ secrets.SSH_USER }} -e ansible_password=${{ secrets.SSH_PASS }} -e tool_name=minikube