name: Provision Tool Infra
on: [push, workflow_dispatch]
jobs:
  Provision:
    runs-on: ubuntu-latest
    steps:
      - run: terraform --version


#name: Provision Tool Infra
#on: [workflow_dispatch]
#jobs:
#  Provision:
#    runs-on: self-hosted
#    steps:
#      - uses: actions/checkout@v4
#      - name: Terraform Init
#        run: terraform init
#      - name: Terraform Apply
#        run: terraform apply -auto-approve
